[package]
name = "aili_model"
version = "0.1.0"
edition = "2024"
authors = ["IWonderWhatThisAPIDoes"]
license = "MIT OR Apache-2.0"

[dependencies]
derive_more = { version = "2.0.1", features = ["debug", "display", "error", "from"] }
