name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test-vis:
    runs-on: ubuntu-latest
    name: Tests (vis)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install Node packages
        run: npm ci
      - name: Run tests
        run: npm test -w vis
