name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-jsapi:
    runs-on: ubuntu-latest
    name: Build JSAPI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build
        run: wasm-pack build jsapi --target bundler
      - name: Save build outputs
        uses: actions/cache/save@v3
        with:
          path: jsapi/pkg
          key: jsapi-package
  
  npm-install:
    runs-on: ubuntu-latest
    name: Install Node packages
    needs: build-jsapi
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load JSAPI package
        uses: actions/cache/restore@v3
        with:
          path: jsapi/pkg
          key: jsapi-package
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install Node packages
        run: npm ci
      - name: Cache installed packages
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node_modules

  test-vis:
    runs-on: ubuntu-latest
    name: Tests (vis)
    needs: npm-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node_modules
      - name: Run tests
        run: npm test -w vis

  doc-vis:
    runs-on: ubuntu-latest
    name: Docs (vis)
    needs: npm-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node_modules
      - name: Check documentation
        run: npm run doc -w vis

  examples-vis:
    runs-on: ubuntu-latest
    name: Examples (vis)
    needs: npm-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node_modules
      - name: Check examples
        run: npm run examples -w vis

  cargo-test:
    runs-on: ubuntu-latest
    name: Tests (Cargo)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --workspace

  clippy:
    runs-on: ubuntu-latest
    name: Clippy lints
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run Clippy lints
        run: cargo clippy --workspace --all-targets --all-features -- --deny warnings

  cargo-fmt:
    runs-on: ubuntu-latest
    name: Format (Cargo)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check 
        run: cargo fmt --all -- --check

  cargo-doc:
    runs-on: ubuntu-latest
    name: Docs (Cargo)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check documentation
        run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --document-private-items --no-deps

  build-demo:
    runs-on: ubuntu-latest
    name: Build Demo
    needs: npm-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node_modules
      - name: Build Demo
        run: npm run build -w demo
