name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-jsapi:
    runs-on: ubuntu-latest
    name: Build JSAPI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build
        run: wasm-pack build jsapi --target bundler --features gdbstate
      - name: Save build outputs
        uses: actions/upload-artifact@v4
        with:
          name: jsapi
          path: jsapi/pkg/
          overwrite: true

  test-hooligan:
    runs-on: ubuntu-latest
    name: Tests (hooligan)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install Node packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Run tests
        run: npm test -w hooligan

  doc-hooligan:
    runs-on: ubuntu-latest
    name: Docs (hooligan)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install Node packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Check documentation
        run: npm run doc -w hooligan

  test-vis:
    runs-on: ubuntu-latest
    name: Tests (vis)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install Node packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Run tests
        run: npm test -w vis

  doc-vis:
    runs-on: ubuntu-latest
    name: Docs (vis)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install Node packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Check documentation
        run: npm run doc -w vis

  examples-vis:
    runs-on: ubuntu-latest
    name: Examples (vis)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install Node packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Check examples
        run: npm run examples -w vis

  cargo-test:
    runs-on: ubuntu-latest
    name: Tests (Cargo)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests, except GDBState
        run: cargo test --workspace --exclude aili-gdbstate
      - name: Run GDBState library tests
        run: cargo test -p aili-gdbstate --lib
  
  gdbstate-test:
    runs-on: ubuntu-latest
    name: Tests (GDBState, integration tests)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Update package manager
        run: sudo apt-get update
      - name: Install GDB
        run: sudo apt-get install gdb --yes
      - name: Run GDBState integration tests
        run: cargo test -p aili-gdbstate --test integration_test

  clippy:
    runs-on: ubuntu-latest
    name: Clippy lints
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run Clippy lints
        run: cargo clippy --workspace --all-targets --all-features -- --deny warnings

  cargo-fmt:
    runs-on: ubuntu-latest
    name: Format (Cargo)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check 
        run: cargo fmt --all -- --check

  cargo-doc:
    runs-on: ubuntu-latest
    name: Docs (Cargo)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check documentation
        run: RUSTDOCFLAGS="-D warnings" cargo doc --workspace --document-private-items --no-deps --all-features

  build-demo:
    runs-on: ubuntu-latest
    name: Build Demo
    needs:
      - build-jsapi
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install Node packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Load JSAPI
        uses: actions/download-artifact@v4
        with:
          name: jsapi
          path: jsapi/pkg
      - name: Build Demo
        run: npm run build -w demo

  doc-debugger:
    runs-on: ubuntu-latest
    name: Docs (debugger)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install Node packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Check documentation
        run: npm run doc -w debugger

  build-debugger:
    runs-on: ubuntu-latest
    name: Build Debugger
    needs:
      - build-jsapi
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Load Node packages
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/puppeteer
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install Node packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Load JSAPI
        uses: actions/download-artifact@v4
        with:
          name: jsapi
          path: jsapi/pkg
      - name: Build Debugger
        run: npm run build -w debugger
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debugger
          path: debugger/dist/
          overwrite: true
