name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test-vis:
    runs-on: ubuntu-latest
    name: Tests (vis)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test -w vis
